/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suppliersInterfaces;

import DBConnect.DBconnect;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mainInterface.MainPage;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author AviShka
 */
public class ReportsSuppliers extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    
    public ReportsSuppliers() {
        initComponents();
          //connect to db
        con=DBconnect.getConnection();
        
        //tea leaf table
         tableLoad();
    }
      public void tableLoad(){
           try{
               
      String sql="SELECT t.sid as 'Supplier Id',a.fname as 'First Name',a.lname as 'Last Name', MONTHNAME(t.Date)as 'Month', SUM(t.TQuantity) as 'Total Stock (KG)', SUM(t.Cost) as 'Total Cost (Rs)' FROM tealeaf t ,activesuppliers a WHERE t.sid = a.sid GROUP BY MONTH(Date),t.sid ";    
       // String sql="SELECT t.Tcid,t.sid,a.fname,t.Date,t.TQuantity,t.Cost FROM tealeaf t ,activesuppliers a WHERE t.sid = a.sid";
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        reporttable.setModel(DbUtils.resultSetToTableModel(rs));
       
            
        }
        catch(Exception e){
            System.out.println("Error");
            //JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reporttable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GenerateInvoiceButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        supplierHome = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idbox = new javax.swing.JLabel();
        namebox = new javax.swing.JLabel();
        lnamebox = new javax.swing.JLabel();
        monthbox = new javax.swing.JLabel();
        quantitybox = new javax.swing.JLabel();
        costbox = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        reporttable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reporttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tcid", "sid", "date", "Tquantity", "rate", "cost"
            }
        ));
        reporttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(reporttable);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(40, 130, 598, 144);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reportjpeg.jpg"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 0, 690, 730);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 692, 728));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Supplier ID          :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("First Name           :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Month                 : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 170, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tea Quantity (KG) :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 442, 160, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Amount (Rs)        :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, 160, -1));

        GenerateInvoiceButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GenerateInvoiceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-powerpoint-48.png"))); // NOI18N
        GenerateInvoiceButton.setText("Generate Invoice");
        GenerateInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateInvoiceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(GenerateInvoiceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, 401, 65));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Supplier Invoice");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-return-48.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 630, 168, 64));

        supplierHome.setBackground(new java.awt.Color(204, 255, 255));
        supplierHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        supplierHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-top-menu-48.png"))); // NOI18N
        supplierHome.setText("Home");
        supplierHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierHomeActionPerformed(evt);
            }
        });
        jPanel1.add(supplierHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, 172, 64));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Last Name           :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/supreports.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        idbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 80, 30));

        namebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 100, 20));

        lnamebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(lnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 110, 20));

        monthbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(monthbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, -1, -1));

        quantitybox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(quantitybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, -1, -1));

        costbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(costbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1187, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reporttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporttableMouseClicked
        
        int r=reporttable.getSelectedRow();
        
       
        try {
        
        String id=reporttable.getValueAt(r, 0).toString();
        String fname=reporttable.getValueAt(r, 1).toString();
        String lname=reporttable.getValueAt(r, 2).toString();
       // Date date = new SimpleDateFormat("yyyy-MM-dd").parse(reporttable.getValueAt(r, 3).toString());
         String month=reporttable.getValueAt(r, 3).toString();
        String quan=reporttable.getValueAt(r, 4).toString();
       String cost=reporttable.getValueAt(r, 5).toString();
        
        
        idbox.setText(id);
        namebox.setText(fname);
        lnamebox.setText(lname);
        monthbox.setText(month);
        //datebox.setDate(date);
        quantitybox.setText(quan+ " Kg");
        costbox.setText("Rs."+cost);
         // quantitybox.getText(quan);
       
        
      
        
        
        } catch (Exception e) {
             System.out.println("Not clicking Error");
        }
        
    }//GEN-LAST:event_reporttableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //back to supplier home page
        SupplierHomePage home = new  SupplierHomePage ();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void GenerateInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateInvoiceButtonActionPerformed

      String id=idbox.getText();
         
     if(id.equals("")){
                JOptionPane.showMessageDialog(null, "Something is Wrong in Invoice"); 
                
         }
        
     else{
          int x=JOptionPane.showConfirmDialog(null, "Do you Print Supplier Invoice?"); 
       
          if(x==0){
            
          

        try{
        
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("SupplierInvoice.pdf"));
            
            document.open();
            Image image= Image.getInstance("reporthead.png"); //Logo
            image.scaleToFit(500, 2500);
            document.add(image );
           
            document.add(new Paragraph("                                                                                               Date :" +new Date().toString()));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("                                      Supplier Invoice",FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD,BaseColor.RED)));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("                                                                                                                                 "));
      
            document.add(new Paragraph("            Supplier id           :  "                +idbox.getText()+ "",FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD,BaseColor.BLACK)));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("            First Name          :  "                   +namebox.getText()+ "\n",FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD,BaseColor.BLACK)));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("            Last Name           :  "      +lnamebox.getText()+ "",FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD,BaseColor.BLACK)));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("            Month                  :  "      +monthbox.getText()+ "",FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD,BaseColor.BLACK)));
            document.add(new Paragraph("                                                                                                                                  "));
            document.add(new Paragraph("            Tea Quantity       :  "      +quantitybox.getText()+ "",FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD,BaseColor.BLACK)));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("            Amount               :   "  +costbox.getText()+ "",FontFactory.getFont(FontFactory.TIMES_BOLD, 14, Font.BOLD,BaseColor.BLACK)));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("                                                                                                                                 "));
            
            
            
            
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("          ..................................                                                        ........................................ "));
            document.add(new Paragraph("             Prepared by                                                         Checked by  ",FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.BOLD,BaseColor.BLACK)));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph(" This is an Automatic Generated Invoice.If there is any problem,Please contact us within 7 days                                                                                                                       "));
            document.add(new Paragraph("  Phone no: 0452 274 364       Fax: + 94 (0) 45 2262210     Email: galpaditennatea@sltnet.lk                                                                                                           "));
            document.close();
            
            JOptionPane.showMessageDialog(null, "Report is Sucess"); 
        
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
               }
        
          
          }
     }   
         
          
                
    }//GEN-LAST:event_GenerateInvoiceButtonActionPerformed

    private void supplierHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierHomeActionPerformed
        MainPage main = new MainPage();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_supplierHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsSuppliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateInvoiceButton;
    private javax.swing.JLabel costbox;
    private javax.swing.JLabel idbox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lnamebox;
    private javax.swing.JLabel monthbox;
    private javax.swing.JLabel namebox;
    private javax.swing.JLabel quantitybox;
    private javax.swing.JTable reporttable;
    private javax.swing.JButton supplierHome;
    // End of variables declaration//GEN-END:variables
}
