/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suppliersInterfaces;


import DBConnect.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.regex.*;
import mainInterface.MainPage;


//import static net.proteanit.sql.DbUtils.resultSetToTableModel;
/**
 *
 * @author AviShka
 */
public class SuppliersAdd extends javax.swing.JFrame {
    
        Connection con ;
        PreparedStatement pst ;
        ResultSet rs;
        
    public SuppliersAdd() {
         
        initComponents();
       
       //connect to the db
       con=DBconnect.getConnection();
       
       
       //load the view table
       Update_table();//view table
       Update_table1();//edit table
       active_table1();//active suppliers list table
      
    // tableLoad();
    }
    
    //view table
    private void Update_table(){
        
        try{
        String sql="SELECT * FROM supplier";
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        tablebox.setModel(DbUtils.resultSetToTableModel(rs));
       
            
        }
        catch(Exception e){
            System.out.println("Update table is not working");
            //JOptionPane.showMessageDialog(null, e);
        }
       
        
        
    }
    //edit table
       private void Update_table1(){
        
        try{
        String sql="SELECT * FROM supplier";
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        tablebox2.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
            System.out.println("Avishka");
            //JOptionPane.showMessageDialog(null, e);
        }
       
        
        
    }   //active suppliers list
         private void active_table1(){
        
        try{
        String sql="SELECT * FROM activesuppliers";
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        tablebox3.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
            System.out.println("Active table is Error");
            //JOptionPane.showMessageDialog(null, e);
        }
       
        
        
    }
       public void clear(){
           
            
            namebox1.setText("");
            lnamebox.setText("");
            agebox.setText("");
            addressbox.setText("");
            phonebox.setText("");
            genderbox.setSelectedItem("Select Gender");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        homepageButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        typebox = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phonebox = new javax.swing.JTextField();
        addressbox = new javax.swing.JTextField();
        ResetSupplierFormButton = new javax.swing.JButton();
        AddSupplierButton = new javax.swing.JButton();
        lnamebox = new javax.swing.JTextField();
        genderbox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        agebox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        namebox1 = new javax.swing.JTextField();
        DemoButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablebox = new javax.swing.JTable();
        searchbox = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        namebox3 = new javax.swing.JTextField();
        agebox2 = new javax.swing.JTextField();
        addressbox2 = new javax.swing.JTextField();
        genderbox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablebox2 = new javax.swing.JTable();
        DeleteButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        phonebox3 = new javax.swing.JTextField();
        SendActiveButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        namebox2 = new javax.swing.JTextField();
        snobox2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablebox3 = new javax.swing.JTable();
        RemoveActiveListButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NEWHEAD.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 150));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        homepageButton.setBackground(new java.awt.Color(255, 255, 255));
        homepageButton.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        homepageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-top-menu-48.png"))); // NOI18N
        homepageButton.setText("Home");
        homepageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepageButtonActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton4.setText("Add Supplier");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton6.setText("Update/Delete Supplier");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton7.setText("View Supplier");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton8.setText("View Active Suppliers");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(255, 255, 204));
        BackButton.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-return-48.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homepageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(homepageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 290, 570));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel3.setText("Last Name       :");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel4.setText("Location          :");

        typebox.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        typebox.setText("Gender            :");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setText("Contact No      :");

        phonebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneboxKeyPressed(evt);
            }
        });

        ResetSupplierFormButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ResetSupplierFormButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-synchronize-48.png"))); // NOI18N
        ResetSupplierFormButton.setText("RESET");
        ResetSupplierFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetSupplierFormButtonActionPerformed(evt);
            }
        });

        AddSupplierButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AddSupplierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-48.png"))); // NOI18N
        AddSupplierButton.setText("ADD");
        AddSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSupplierButtonActionPerformed(evt);
            }
        });

        genderbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel11.setText("Age                  :");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel13.setText("First Name      :");

        DemoButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        DemoButton.setText("Demo");
        DemoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typebox)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(AddSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ResetSupplierFormButton))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agebox, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressbox, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phonebox, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namebox1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addComponent(DemoButton)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(namebox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DemoButton))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(lnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(agebox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(addressbox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phonebox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderbox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typebox))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSupplierButton)
                    .addComponent(ResetSupplierFormButton))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel5);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tablebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tablebox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Supplier No", "Name", "Age", "Location", "Phone No", "Gender"
            }
        ));
        tablebox.setRowSelectionAllowed(false);
        tablebox.setUpdateSelectionOnSort(false);
        tablebox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableboxMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablebox);

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-48.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Supplier No :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("First Name  :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Location     :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Contact No :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Gender      :");

        namebox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namebox3ActionPerformed(evt);
            }
        });

        genderbox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        genderbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderbox2ActionPerformed(evt);
            }
        });

        tablebox2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "sno", "name", "age", "location", "phone", "gender"
            }
        ));
        tablebox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablebox2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablebox2);

        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-48.png"))); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-restart-48 (1).png"))); // NOI18N
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Age           :");

        SendActiveButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        SendActiveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-ok-48.png"))); // NOI18N
        SendActiveButton.setText("Send Active List");
        SendActiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActiveButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Last  Name :");

        namebox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namebox2ActionPerformed(evt);
            }
        });

        snobox2.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(38, 38, 38)
                                .addComponent(snobox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(genderbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namebox2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(namebox3)
                            .addComponent(agebox2)
                            .addComponent(addressbox2)
                            .addComponent(phonebox3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(UpdateButton)
                                    .addGap(139, 139, 139))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(SendActiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(snobox2))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(namebox2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(namebox3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(agebox2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addressbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phonebox3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(SendActiveButton)
                        .addGap(66, 66, 66)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        tablebox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tablebox3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "sid", "name", "age", "location", "phone", "gender"
            }
        ));
        jScrollPane3.setViewportView(tablebox3);

        RemoveActiveListButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        RemoveActiveListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-48.png"))); // NOI18N
        RemoveActiveListButton.setText("Remove from List");
        RemoveActiveListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActiveListButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Active Suppliers List");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(RemoveActiveListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel16)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(RemoveActiveListButton)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 780, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void infoMessage(String message,String title){
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tableboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableboxMouseClicked
        boolean a=tablebox.isEditing();//view table not editing
        
        if(a==false)
        {
            JOptionPane.showMessageDialog(null, "You Can't Edit this Table");
        }
    }//GEN-LAST:event_tableboxMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void AddSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSupplierButtonActionPerformed
 
     //add suppliers
       
        String name=namebox1.getText();
        String lname=lnamebox.getText();
        String age=agebox.getText();
        String address=addressbox.getText();
        String phone=phonebox.getText();
        String gender=genderbox.getSelectedItem().toString();
    
    
        Pattern alphabet = Pattern.compile("^[a-zA-Z]+$");
        Pattern numbers = Pattern.compile("^[0-9]+$");
            
         Matcher name1 = alphabet.matcher(name);
         Matcher lname1 =alphabet.matcher(lname);
         Matcher add1 = alphabet.matcher(address);
         Matcher age1 = numbers.matcher(age);
         Matcher phone1= numbers.matcher(phone);
            
            
            if (!name1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter First Name Correctly");
                return;
            } 
             if (!lname1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Last Name Correctly");
                return;
            } 
             if (!add1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Location Correctly");
                return;
            } 
       
            if (!age1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Age Correctly");
                return;
            } 
            if (!phone1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Phone Number Correctly");
                return;
            } 
             if (gender.equals("Select Gender")){
                JOptionPane.showMessageDialog(null, "Please Select the Gender");
                return;
            } 
    
     
        try{
         
            String q ="INSERT INTO supplier (fname,lname,age,location,phone,gender)values ('"+name+"','"+lname+"','"+age+"','"+address+"','"+phone+"','"+gender+"')";
            pst= con.prepareStatement(q);
            // pst.execute();
            int x=pst.executeUpdate(q);
            System.out.println(x);
            if(x==1){
                 JOptionPane.showMessageDialog(null, "Sucessfully Added");
            }
            else{
                // infoMessage("Error","Alert");
            }
            Update_table();//update view table
            Update_table1();//update edit table
            
            
            //After send data to DB textfield empty
          clear();
          

        }catch(Exception e){
            System.out.println("Not connected");
        }
      
    }//GEN-LAST:event_AddSupplierButtonActionPerformed

    private void tablebox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablebox2MouseClicked
        
        int r =tablebox2.getSelectedRow();
        
        String sid=tablebox2.getValueAt(r, 0).toString();
        String name=tablebox2.getValueAt(r, 1).toString();
        String lname=tablebox2.getValueAt(r, 2).toString();
        String age=tablebox2.getValueAt(r, 3).toString();
        String address=tablebox2.getValueAt(r, 4).toString();
        String phone=tablebox2.getValueAt(r, 5).toString();
        String gender=tablebox2.getValueAt(r, 6).toString();
        
        snobox2.setText(sid);
        namebox2.setText(name);
        namebox3.setText(lname);
        agebox2.setText(age);
        addressbox2.setText(address);
        phonebox3.setText(phone);
        genderbox2.setSelectedItem(gender);
        
    }//GEN-LAST:event_tablebox2MouseClicked

    private void namebox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namebox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namebox3ActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to Update?");
        String sid=snobox2.getText();
        //String 
        if(x==0){
            
        String name=namebox2.getText();
        String lname=namebox3.getText();
        String age=agebox2.getText();
        String address=addressbox2.getText();
        String phone= phonebox3.getText();
        String gender=genderbox2.getSelectedItem().toString();
        
         Pattern alphabet = Pattern.compile("^[a-zA-Z]+$");
         Pattern numbers = Pattern.compile("^[0-9]+$");
            
         Matcher name1 = alphabet.matcher(name);
         Matcher lname1 =alphabet.matcher(lname);
         Matcher add1 = alphabet.matcher(address);
         Matcher age1 = numbers.matcher(age);
         Matcher phone1= numbers.matcher(phone);
            
            if (!name1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter First Name Correctly");
                return;
            } 
              
            if (!lname1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Last Name Correctly");
                return;
            } 
             if (!add1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Location Correctly");
                return;
            } 
       
            if (!age1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Age Correctly");
                return;
            } 
            if (!phone1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Phone Number Correctly");
                return;
            } 
            if (gender.equals("Select Gender")){
                JOptionPane.showMessageDialog(null, "Please Select the Gender");
                return;
            } 
            
        
     
        
        String sql="UPDATE supplier SET fname = '"+name +"',lname = '"+lname +"',age = '"+ age +"',location = '"+ address +"',phone = '"+ phone +"',gender = '"+ gender +"' where sid = '"+sid+"'";
        try{
            
        pst=con.prepareStatement(sql);
        pst.execute();
        Update_table();
        Update_table1();
        
        clear();
        }
        catch(SQLException e){
            System.out.println("Updating Error");
            
        }
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        
        //DELETE BUTTON
        int x=JOptionPane.showConfirmDialog(null, "Do you really want to Delete this?");
        if(x==0){
            String id=snobox2.getText();
            
            String sql="DELETE from supplier where sid ='" +id+ "'";
            try{
                 pst=con.prepareStatement(sql);
                 pst.execute();
                 Update_table();
                 Update_table1();
            }
            catch(Exception e){
                System.out.println("Delete Button Error");
            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        
        String name=searchbox.getText();
        
        String sql="Select sid,fname,lname,age,location,phone,gender from supplier where fname LIKE '%"+name+"%'";
        try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
             tablebox.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            System.out.println("Search box error");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void SendActiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActiveButtonActionPerformed
      
        //Send suppliers to Active lise
        int x=JOptionPane.showConfirmDialog(null, "Do you really want to send Active Suppliers List?");
        if(x==0){
        String id=snobox2.getText();
        String name=namebox2.getText();
        String lname=namebox3.getText();
        String age=agebox2.getText();
        String address=addressbox2.getText();
        String phone= phonebox3.getText();
        String gender=genderbox2.getSelectedItem().toString();
            
         Pattern alphabet = Pattern.compile("^[a-zA-Z]+$");
         Pattern numbers = Pattern.compile("^[0-9]+$");
            
         Matcher name1 = alphabet.matcher(name);
         Matcher lname1 =alphabet.matcher(lname);
         Matcher add1 = alphabet.matcher(address);
         Matcher age1 = numbers.matcher(age);
         Matcher phone1= numbers.matcher(phone);
            
            if (!name1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter First Name Correctly");
                return;
            } 
              
            if (!lname1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Last Name Correctly");
                return;
            } 
             if (!add1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Address Correctly");
                return;
            } 
       
            if (!age1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Age Correctly");
                return;
            } 
            if (!phone1.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Phone Number Correctly");
                return;
            } 
           
            
            try{
                String sql ="INSERT INTO activesuppliers(sid,fname,lname,age,location,phone,gender)values ('"+id+"','"+name+"','"+lname+"','"+age+"','"+address+"','"+phone+"','"+gender+"')";
            pst= con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Sucessfully Added to Active List");
            active_table1();
            }
            catch(Exception e){
               JOptionPane.showMessageDialog(null, "Invalid input");
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_SendActiveButtonActionPerformed
    
    //Delete suppliers from Active List
    private void RemoveActiveListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActiveListButtonActionPerformed
       int row =tablebox3.getSelectedRow();
        String id=tablebox3.getModel().getValueAt(row,0).toString();
        String sql="DELETE from activesuppliers where sid ='" +id+ "'";
        try{
            pst=con.prepareStatement(sql);
                 pst.execute();
                 JOptionPane.showMessageDialog(null,"Do you want to Inactive this supplier?");
                 active_table1();
            
        }
         catch(Exception e){
                System.out.println("Delete Button Error");
         }
    
    }//GEN-LAST:event_RemoveActiveListButtonActionPerformed

    private void ResetSupplierFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetSupplierFormButtonActionPerformed
        namebox1.setText("");
        lnamebox.setText("");
        agebox.setText("");
        addressbox.setText("");
        phonebox.setText("");
        genderbox.setSelectedItem("Select Gender");
    }//GEN-LAST:event_ResetSupplierFormButtonActionPerformed

    private void phoneboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneboxKeyPressed
        //action when key is press
        
        
    }//GEN-LAST:event_phoneboxKeyPressed

    private void namebox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namebox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namebox2ActionPerformed

    private void genderbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderbox2ActionPerformed

    private void homepageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepageButtonActionPerformed
        
        MainPage main = new MainPage();
        main.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_homepageButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        SupplierHomePage home = new  SupplierHomePage ();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void DemoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemoButtonActionPerformed
        
        namebox1.setText("Mahinda");
        lnamebox.setText("Rajapaksha");
        agebox.setText("72");
        addressbox.setText("Hambanthota");
        phonebox.setText("0112295273");
        genderbox.setSelectedItem("Male");
    }//GEN-LAST:event_DemoButtonActionPerformed
       
    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuppliersAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuppliersAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuppliersAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuppliersAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            
            public void run() {
                new SuppliersAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSupplierButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DemoButton;
    private javax.swing.JButton RemoveActiveListButton;
    private javax.swing.JButton ResetSupplierFormButton;
    private javax.swing.JButton SendActiveButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField addressbox;
    private javax.swing.JTextField addressbox2;
    private javax.swing.JTextField agebox;
    private javax.swing.JTextField agebox2;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JComboBox<String> genderbox2;
    private javax.swing.JButton homepageButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lnamebox;
    private javax.swing.JTextField namebox1;
    private javax.swing.JTextField namebox2;
    private javax.swing.JTextField namebox3;
    private javax.swing.JTextField phonebox;
    private javax.swing.JTextField phonebox3;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchbox;
    private javax.swing.JLabel snobox2;
    private javax.swing.JTable tablebox;
    private javax.swing.JTable tablebox2;
    private javax.swing.JTable tablebox3;
    private javax.swing.JLabel typebox;
    // End of variables declaration//GEN-END:variables

    }


