/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suppliersInterfaces;

import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import mainInterface.MainPage;

/**
 *
 * @author AviShka
 */
public class SupplierHomePage extends javax.swing.JFrame {

    /**
     * Creates new form SupplierHomePage
     */
    public SupplierHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TeaLeafbutton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        supplierButton = new javax.swing.JButton();
        ReportsButton = new javax.swing.JButton();
        TeaHomeBackButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        TeaLeafbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tea leaf collecting.jpg"))); // NOI18N
        TeaLeafbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaLeafbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(TeaLeafbutton);
        TeaLeafbutton.setBounds(890, 150, 200, 200);

        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leafbutton.jpg"))); // NOI18N
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HomeButton);
        HomeButton.setBounds(640, 390, 200, 200);

        supplierButton.setBackground(new java.awt.Color(255, 255, 255));
        supplierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SuppllierButton.jpg"))); // NOI18N
        supplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierButtonActionPerformed(evt);
            }
        });
        jPanel1.add(supplierButton);
        supplierButton.setBounds(640, 150, 200, 200);

        ReportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reports.jpg"))); // NOI18N
        ReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ReportsButton);
        ReportsButton.setBounds(890, 390, 200, 200);

        TeaHomeBackButton.setBackground(new java.awt.Color(255, 255, 255));
        TeaHomeBackButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TeaHomeBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-top-menu-48.png"))); // NOI18N
        TeaHomeBackButton.setText("Back to Home Page");
        TeaHomeBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaHomeBackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(TeaHomeBackButton);
        TeaHomeBackButton.setBounds(640, 630, 450, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SupplierHomePage.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1150, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void supplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierButtonActionPerformed
        
        SuppliersAdd supplier = new  SuppliersAdd();
        supplier.setVisible(true);
        this.dispose();
        
                
    }//GEN-LAST:event_supplierButtonActionPerformed

    private void TeaLeafbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaLeafbuttonActionPerformed
        //go to tea collect page
        TeaCollect tea = new  TeaCollect();
        tea.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TeaLeafbuttonActionPerformed

    private void ReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsButtonActionPerformed
        // go to tea reports page
        ReportsSuppliers report = new  ReportsSuppliers();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReportsButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        TeaLeafStock stock = new TeaLeafStock();
        stock.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void TeaHomeBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaHomeBackButtonActionPerformed
        MainPage main = new MainPage();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TeaHomeBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton ReportsButton;
    private javax.swing.JButton TeaHomeBackButton;
    private javax.swing.JButton TeaLeafbutton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton supplierButton;
    // End of variables declaration//GEN-END:variables
}
