/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suppliersInterfaces;

import DBConnect.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import mainInterface.MainPage;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author AviShka
 */
public class TeaCollect extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public TeaCollect() {
        initComponents();
        
        //connect to db
        con=DBconnect.getConnection();
        
        //tea leaf table
         tableLoad();
    
    }
    public void tableLoad(){
           try{
        String sql="SELECT tcid,sid,Date,Tquantity,DailyRate,Cost FROM tealeaf ";
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        leaftable.setModel(DbUtils.resultSetToTableModel(rs));
       
            
        }
        catch(Exception e){
            System.out.println("Table load error");
            //JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void clear(){
        tcidbox.setText("");
        supbox.setText("");
        datebox.setDate(null);
        quanbox.setText("");
        costbox.setText("");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        supbox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        quanbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        viewId = new javax.swing.JButton();
        TeaCollectAdd = new javax.swing.JButton();
        TeaCollectUpdate = new javax.swing.JButton();
        datebox = new com.toedter.calendar.JDateChooser();
        costbox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leaftable = new javax.swing.JTable();
        TeaCollectClear = new javax.swing.JButton();
        TeaCollectDelete = new javax.swing.JToggleButton();
        tcidbox = new javax.swing.JLabel();
        TeaCollectBackButton = new javax.swing.JButton();
        TeaCollectHomeButton = new javax.swing.JButton();
        searchbox = new javax.swing.JTextField();
        TeaCollectsearch = new javax.swing.JButton();
        TeaCollectDemo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TCID");

        supbox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supboxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tea Supplier ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Tea Quantity");

        quanbox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("KG");

        jLabel6.setBackground(new java.awt.Color(102, 255, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Teacolethead.jpg"))); // NOI18N

        viewId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-view-48_1.png"))); // NOI18N
        viewId.setText("View ID");
        viewId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewIdActionPerformed(evt);
            }
        });

        TeaCollectAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TeaCollectAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-48.png"))); // NOI18N
        TeaCollectAdd.setText("Add");
        TeaCollectAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaCollectAddActionPerformed(evt);
            }
        });

        TeaCollectUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TeaCollectUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-available-updates-48.png"))); // NOI18N
        TeaCollectUpdate.setText("Update");
        TeaCollectUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaCollectUpdateActionPerformed(evt);
            }
        });

        datebox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        costbox.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Daily Rate(Rs.)");

        leaftable.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        leaftable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TCID", "SID", "Date", "Tea Quantity(KG)", "DailyRate", "Cost"
            }
        ));
        leaftable.setToolTipText("");
        leaftable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leaftableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(leaftable);

        TeaCollectClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TeaCollectClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sync-48.png"))); // NOI18N
        TeaCollectClear.setText("Clear");
        TeaCollectClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaCollectClearActionPerformed(evt);
            }
        });

        TeaCollectDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TeaCollectDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-48.png"))); // NOI18N
        TeaCollectDelete.setText("Delete");
        TeaCollectDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaCollectDeleteActionPerformed(evt);
            }
        });

        tcidbox.setText("ID");

        TeaCollectBackButton.setBackground(new java.awt.Color(255, 255, 204));
        TeaCollectBackButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TeaCollectBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-return-48.png"))); // NOI18N
        TeaCollectBackButton.setText("Back");
        TeaCollectBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaCollectBackButtonActionPerformed(evt);
            }
        });

        TeaCollectHomeButton.setBackground(new java.awt.Color(204, 255, 255));
        TeaCollectHomeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TeaCollectHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-top-menu-48.png"))); // NOI18N
        TeaCollectHomeButton.setText("Home");
        TeaCollectHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaCollectHomeButtonActionPerformed(evt);
            }
        });

        TeaCollectsearch.setText("Search");
        TeaCollectsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaCollectsearchActionPerformed(evt);
            }
        });

        TeaCollectDemo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TeaCollectDemo.setText("Demo");
        TeaCollectDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaCollectDemoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TeaCollectHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TeaCollectUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeaCollectAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(tcidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TeaCollectsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TeaCollectBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TeaCollectDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TeaCollectClear, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(datebox, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quanbox, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(supbox)
                                    .addComponent(costbox))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TeaCollectDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(viewId, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tcidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeaCollectDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeaCollectsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(supbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(viewId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(datebox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(quanbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(costbox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeaCollectAdd)
                            .addComponent(TeaCollectClear))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeaCollectDelete)
                            .addComponent(TeaCollectUpdate)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeaCollectBackButton)
                    .addComponent(TeaCollectHomeButton))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void supboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supboxActionPerformed

    private void viewIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewIdActionPerformed
        ViewIdSuppliers m1=new ViewIdSuppliers();
        m1.setVisible(true);
        
    }//GEN-LAST:event_viewIdActionPerformed

    private void TeaCollectAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaCollectAddActionPerformed
       
  
        String supId = supbox.getText();
        
        Pattern numbers = Pattern.compile("^[0-9]+$");
        Matcher supid= numbers.matcher(supId);

           //Supplier Id validate
         if (!supid.find()){
                JOptionPane.showMessageDialog(null, "Please supplier ID Correctly");
                return;
          } 
        
    
       //Tea Quantity Validate
        double tquantity =0;
       
        
        try{
         tquantity =Double.parseDouble(quanbox.getText());
        }
        catch(NumberFormatException | NullPointerException e){
            JOptionPane.showMessageDialog(null, "Enter Numbers for Quantity");
            return;
        }
        
        
        //Daily Rate Validate
         double rate =0;
         
         try{
         
         rate =Double.parseDouble(costbox.getText());
        
        }
        catch(NumberFormatException | NullPointerException e){
            JOptionPane.showMessageDialog(null, "Enter Numbers for Rate");
            return;
        }
        
         
         //Minus Values Validate
       if(tquantity <= 0 || rate <=0){
           JOptionPane.showMessageDialog(null, "Minus Values Can't Submit");
            return;
       }
       
       
        //Tea cost calculation
        double cost= tquantity * rate;    
        
        //Date validation
        String theDate="";
        
        try{
        Date date=datebox.getDate();
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
        theDate=dateFormat.format(date);
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please Enter Date");
            return;
        }
        
          try{
       
            
            //Tea stock table
            String q ="INSERT INTO tealeaf (sid,Date,TQuantity,DailyRate,Cost)values ('"+supId+"','"+theDate+"','"+tquantity+"','"+rate+"','"+cost+"')";
            pst = con.prepareStatement(q);
            pst.execute();
            
            tableLoad();//tea leaf table loading
            clear(); //clear textfields
            
            
            //Production Table
            String q1 ="INSERT INTO pro_supplied ( Date,Weight)values ('"+theDate+"','"+tquantity+"')";
            pst = con.prepareStatement(q1);
            pst.execute();
            
            
            //Finance table
            String sql = "INSERT INTO finance_tealeaf (year, month, total) SELECT YEAR(Date)as 'Year',MONTHNAME(Date)as 'Month', SUM(Cost) as 'Total value (Rs)' FROM tealeaf GROUP BY MONTH(Date),YEAR(Date) ";
            pst = con.prepareStatement(sql);
            pst.execute();
            
            
            
            

        }catch(Exception e){
            System.out.println("Not connecteded");
              System.out.println(e);
        }
    }//GEN-LAST:event_TeaCollectAddActionPerformed

    private void leaftableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaftableMouseClicked
        
        //take table details to form again
        try {
        int r=leaftable.getSelectedRow();
        
        String tcid=leaftable.getValueAt(r, 0).toString();
        String supId=leaftable.getValueAt(r, 1).toString();
        Date date = new SimpleDateFormat("yyyy-MM-dd").parse(leaftable.getValueAt(r, 2).toString());
        String tquantity=leaftable.getValueAt(r, 3).toString();
        String rate= leaftable.getValueAt(r, 4).toString();
        
        
        tcidbox.setText(tcid);
        supbox.setText(supId);
        datebox.setDate(date);
        quanbox.setText(tquantity);
        costbox.setText(rate);
        
        } catch (Exception e) {
          System.out.println("Not clicking");
        }
       
        TeaCollectAdd.setEnabled(false);
        
      
   
    }//GEN-LAST:event_leaftableMouseClicked

    private void TeaCollectUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaCollectUpdateActionPerformed
        
// updating table
        
        int x=JOptionPane.showConfirmDialog(null, "Do you want to really update?");
        String tcid=tcidbox.getText();
        
        if(x==0){
   
        String supId =supbox.getText();
     
       
        Pattern numbers = Pattern.compile("^[0-9]+$");
        Matcher supid= numbers.matcher(supId);
        
        
         if (!supid.find()){
                JOptionPane.showMessageDialog(null, "Please supplier ID Correctly");
                return;
            } 
       
         //Tea Quantity Validate
        double tquantity =0;
        
        
        try{
         tquantity =Double.parseDouble(quanbox.getText());
         
        
        }
        catch(NumberFormatException | NullPointerException e){
            JOptionPane.showMessageDialog(null, "Enter Numbers for Quantity");
            return;
        }
        
        //Tea Rate Validate
        double rate =0;
        
         try{
       
         rate =Double.parseDouble(costbox.getText());
        
        }
        catch(NumberFormatException | NullPointerException e){
            JOptionPane.showMessageDialog(null, "Enter Numbers for Rate");
            return;
        }
        
        
        
           //Minus Values Validate
       if(tquantity <= 0 || rate <=0){
           JOptionPane.showMessageDialog(null, "Minus Values Can't Submit");
            return;
       }
       
       //Cost 
        double cost= tquantity * rate;    
        
        String theDate="";
        
        try{
        Date date=datebox.getDate();
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
        theDate=dateFormat.format(date);
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please Enter Date");
            return;
        }
       
        
        String sql="UPDATE tealeaf SET sid = '"+supId +"',Date= '"+ theDate +"',TQuantity= '"+ tquantity +"',DailyRate = '"+ rate +"',Cost = '"+ cost +"' where Tcid = '"+tcid+"'";
        try{
            
        pst=con.prepareStatement(sql);
        pst.execute();
        
        String sql1 = "INSERT INTO finance_tealeaf (year, month, total) SELECT YEAR(Date)as 'Year',MONTHNAME(Date)as 'Month', SUM(Cost) as 'Total value (Rs)' FROM tealeaf GROUP BY MONTH(Date),YEAR(Date) ";
        pst = con.prepareStatement(sql1);
        pst.execute();
        
        tableLoad();
        clear();
        }
        catch(SQLException e){
            System.out.println("tea leaf table error");
            
        }
        TeaCollectAdd.setEnabled(true);
        }
        else{
            TeaCollectAdd.setEnabled(true);
        }
    }//GEN-LAST:event_TeaCollectUpdateActionPerformed

    private void TeaCollectClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaCollectClearActionPerformed
        
     
        clear();
        TeaCollectAdd.setEnabled(true);
        
    }//GEN-LAST:event_TeaCollectClearActionPerformed

    private void TeaCollectDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaCollectDeleteActionPerformed
        //DELETE BUTTON
        int x=JOptionPane.showConfirmDialog(null, "Do you really want to Delete this?");
        
        if(x==0){
            
            String tcid=tcidbox.getText();
            
            String sql="DELETE from tealeaf where Tcid ='" +tcid+ "'";
            try{
                 pst=con.prepareStatement(sql);
                 pst.execute();
                 
                 String sql1 = "INSERT INTO finance_tealeaf (year, month, total) SELECT YEAR(Date)as 'Year',MONTHNAME(Date)as 'Month', SUM(Cost) as 'Total value (Rs)' FROM tealeaf GROUP BY MONTH(Date),YEAR(Date) ";
                 pst = con.prepareStatement(sql1);
                 pst.execute();
            
                 tableLoad();
            }
            catch(Exception e){
                System.out.println("Delete Button Error");
            }
             clear();
        TeaCollectAdd.setEnabled(true);
        }
        else{
             clear();
           TeaCollectAdd.setEnabled(true);
        }
        
    }//GEN-LAST:event_TeaCollectDeleteActionPerformed

    private void TeaCollectBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaCollectBackButtonActionPerformed
            //back to supplier home page
        SupplierHomePage home = new  SupplierHomePage ();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TeaCollectBackButtonActionPerformed

    private void TeaCollectsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaCollectsearchActionPerformed
           
        String id=searchbox.getText();
        
        Pattern numbers = Pattern.compile("^[0-9]+$");
        Matcher idsearch = numbers.matcher(id);
        
           if (!idsearch.find()){
                JOptionPane.showMessageDialog(null, "Please Enter Supplier ID Correctly");
                return;
            } 
       
        
        String sql="Select * from tealeaf where sid = '"+id+"'";
        try{
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            
            leaftable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            System.out.println("Search box error");
        }
         
    }//GEN-LAST:event_TeaCollectsearchActionPerformed

    private void TeaCollectHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaCollectHomeButtonActionPerformed
        MainPage main = new MainPage();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TeaCollectHomeButtonActionPerformed

    private void TeaCollectDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaCollectDemoActionPerformed
        
        supbox.setText("1");
        datebox.setDate(null);
        quanbox.setText("100");
        costbox.setText("70");
    }//GEN-LAST:event_TeaCollectDemoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeaCollect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeaCollect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeaCollect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeaCollect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeaCollect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TeaCollectAdd;
    private javax.swing.JButton TeaCollectBackButton;
    private javax.swing.JButton TeaCollectClear;
    private javax.swing.JToggleButton TeaCollectDelete;
    private javax.swing.JButton TeaCollectDemo;
    private javax.swing.JButton TeaCollectHomeButton;
    private javax.swing.JButton TeaCollectUpdate;
    private javax.swing.JButton TeaCollectsearch;
    private javax.swing.JTextField costbox;
    private com.toedter.calendar.JDateChooser datebox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable leaftable;
    private javax.swing.JTextField quanbox;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField supbox;
    private javax.swing.JLabel tcidbox;
    private javax.swing.JButton viewId;
    // End of variables declaration//GEN-END:variables
}
