/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suppliersInterfaces;

import DBConnect.DBconnect;
import java.util.Date;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document; 
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import mainInterface.MainPage;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author AviShka
 */
public class TeaLeafStock extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public TeaLeafStock() {
        initComponents();
        
         con=DBconnect.getConnection();
         active_table1();
         monthTable();
    }
    
    //Daily Tea Leaf Stock Amount
     private void active_table1(){
        
        try{
        String sql="SELECT Date, SUM(TQuantity) as 'Total Stock (KG)',DailyRate, SUM(Cost) as 'Total Cost (Rs)' FROM tealeaf GROUP BY Date";
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        stocktable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
            System.out.println("Avishka");
            //JOptionPane.showMessageDialog(null, e);
        }
        
 
    }
     
     //Monthly Tea Leaf Stock Amount
     private void monthTable(){
         
          try{
        String sql="SELECT YEAR(Date)as 'Year',MONTHNAME(Date)as 'Month', SUM(TQuantity) as 'Total Stock (KG)', SUM(Cost) as 'Total Cost (Rs)' FROM tealeaf GROUP BY MONTH(Date),YEAR(Date) ";
                
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        monthtable.setModel(DbUtils.resultSetToTableModel(rs));
            
        }
        catch(Exception e){
            System.out.println("Avishka");
            //JOptionPane.showMessageDialog(null, e);
        }
         
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stocktable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        monthtable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        homebutton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        PrintMonthlyButton = new javax.swing.JButton();
        PrintDailyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        stocktable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        stocktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stocktable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stocktableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stocktable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 200, 530, 230);

        monthtable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        monthtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Month", "Tquantity", "Cost"
            }
        ));
        monthtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthtableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(monthtable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(610, 200, 520, 230);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Monthly Tea Stock Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(710, 160, 320, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Daily Tea Stock Details");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 160, 290, 30);

        homebutton.setBackground(new java.awt.Color(204, 255, 255));
        homebutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-top-menu-48.png"))); // NOI18N
        homebutton.setText("Home");
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(homebutton);
        homebutton.setBounds(760, 620, 160, 70);

        BackButton.setBackground(new java.awt.Color(255, 255, 204));
        BackButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-return-48.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton);
        BackButton.setBounds(970, 620, 150, 70);

        PrintMonthlyButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PrintMonthlyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-powerpoint-48.png"))); // NOI18N
        PrintMonthlyButton.setText("Print Monthly Tea Stock");
        PrintMonthlyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintMonthlyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PrintMonthlyButton);
        PrintMonthlyButton.setBounds(400, 620, 310, 70);

        PrintDailyButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PrintDailyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-print-48.png"))); // NOI18N
        PrintDailyButton.setText("Print Daily Tea Stock");
        PrintDailyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintDailyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PrintDailyButton);
        PrintDailyButton.setBounds(40, 620, 310, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LeafStock.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1160, 720);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        MainPage main = new MainPage();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homebuttonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        SupplierHomePage home = new  SupplierHomePage ();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void stocktableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocktableMouseClicked
           boolean a=stocktable.isEditing();//view table not editing
        
        if(a==false)
        {
            JOptionPane.showMessageDialog(null, "You Can't Edit this Table");
        }
                                         

    }//GEN-LAST:event_stocktableMouseClicked

    private void monthtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthtableMouseClicked
             boolean a=monthtable.isEditing();//view table not editing
        
        if(a==false)
        {
            JOptionPane.showMessageDialog(null, "You Can't Edit this Table");
        }
             
    }//GEN-LAST:event_monthtableMouseClicked

    private void PrintDailyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintDailyButtonActionPerformed

 
      try{
        String sql="SELECT Date, SUM(TQuantity) as 'Total Stock (KG)',DailyRate, SUM(Cost) as 'Total Cost (Rs)' FROM tealeaf GROUP BY Date";
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        //stocktable.setModel(DbUtils.resultSetToTableModel(rs));
        ResultSetMetaData rsmd=rs.getMetaData();
        int colNo=rsmd.getColumnCount();
            
         int rowNo=0;
         while(rs.next()){
         rowNo++;
         }
         rs.first();
            
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("DailyTeaReport.pdf"));
            
            document.open();
            Image image= Image.getInstance("reporthead.png"); //Logo
            image.scaleToFit(500, 2500);
            document.add(image );
           
            document.add(new Paragraph("                                                                                               Date :" +new Date().toString()));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("                                                Daily Tea Stock Details",FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.BOLD,BaseColor.GREEN)));
            document.add(new Paragraph("                                                                                                                                 "));
            
            PdfPTable table=new PdfPTable(4);
            table.addCell(new Paragraph("Date",FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD,BaseColor.BLACK)));
            table.addCell(new Paragraph("Tea Stock(KG)",FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD,BaseColor.BLACK)));
            table.addCell(new Paragraph("Daily Rate(Rs.)",FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD,BaseColor.BLACK)));
            table.addCell(new Paragraph("Total Cost(Rs.)",FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD,BaseColor.BLACK)));
           
            
            
            for(int i=0; i < rowNo; i++){
                table.addCell(""+rs.getString(1));
                table.addCell(""+rs.getString(2));
                table.addCell(""+rs.getString(3));
                table.addCell(""+rs.getString(4));
                rs.next();
            }
            document.add(table);
              
            document.add(new Paragraph("  "));
            document.add(new Paragraph("  "));
            document.add(new Paragraph("  "));
            
            document.add(new Paragraph("                ...................................                                              ...................................",FontFactory.getFont(FontFactory.TIMES_BOLD, 14,Font.BOLD, BaseColor.BLACK)));
            
            document.add(new Paragraph("                       Prepared By                                                            Checked By",FontFactory.getFont(FontFactory.TIMES_BOLD, 14,Font.BOLD, BaseColor.BLACK)));
            document.add(new Paragraph("  "));
            document.add(new Paragraph("  "));
            document.add(new Paragraph("  "));
            document.add(new Paragraph("                This is an Automatic Generated Invoice.   If there is any problem ,Please contact us..."));
            document.add(new Paragraph("                 Phone no : 0452274364   Fax : +94 (0)  45 2262210   Email : galpaditenna@gmail.com"));
            
            document.close();
            
            JOptionPane.showMessageDialog(null, "Report is Sucess");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
               }
    }//GEN-LAST:event_PrintDailyButtonActionPerformed

    private void PrintMonthlyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintMonthlyButtonActionPerformed
         try{
         String sql="SELECT YEAR(Date)as 'Year',MONTHNAME(Date)as 'Month', SUM(TQuantity) as 'Total Stock (KG)', SUM(Cost) as 'Total Cost (Rs)' FROM tealeaf GROUP BY MONTH(Date),YEAR(Date) ";
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        //stocktable.setModel(DbUtils.resultSetToTableModel(rs));
        ResultSetMetaData rsmd=rs.getMetaData();
        int colNo=rsmd.getColumnCount();
            
         int rowNo=0;
         while(rs.next()){
         rowNo++;
         }
         rs.first();
            
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("MonthlyTeaReport.pdf"));
            
            document.open();
            Image image= Image.getInstance("reporthead.png"); //Logo
            image.scaleToFit(500, 2500);
            document.add(image );
           
            document.add(new Paragraph("                                                                                               Date :" +new Date().toString()));
            document.add(new Paragraph("---------------------------------------------------------------------------------------------------------------------------------"));
            document.add(new Paragraph("                                                                                                                                 "));
            document.add(new Paragraph("                                            Monthly Tea Stock Details",FontFactory.getFont(FontFactory.TIMES_BOLD, 16, Font.BOLD,BaseColor.GREEN)));
            document.add(new Paragraph("                                                                                                                                 "));
            
            PdfPTable table=new PdfPTable(4);
            table.addCell(new Paragraph("Year",FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD,BaseColor.BLACK)));
            table.addCell(new Paragraph("Month",FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD,BaseColor.BLACK)));
            table.addCell(new Paragraph("Tea Stock(KG)",FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD,BaseColor.BLACK)));
            table.addCell(new Paragraph("Total Cost(Rs.)",FontFactory.getFont(FontFactory.TIMES_BOLD, 12, Font.BOLD,BaseColor.BLACK)));
        
            
            for(int i=0; i < rowNo; i++){
                table.addCell(""+rs.getString(1));
                table.addCell(""+rs.getString(2));
                table.addCell(""+rs.getString(3));
                table.addCell(""+rs.getString(4));
                rs.next();
            }
            document.add(table);
            
            document.add(new Paragraph("  "));
            document.add(new Paragraph("  "));
            document.add(new Paragraph("  "));
                    
            document.add(new Paragraph("                ...................................                                              ...................................",FontFactory.getFont(FontFactory.TIMES_BOLD, 14,Font.BOLD, BaseColor.BLACK)));
            
            document.add(new Paragraph("                       Prepared By                                                            Checked By",FontFactory.getFont(FontFactory.TIMES_BOLD, 14,Font.BOLD, BaseColor.BLACK)));
            document.add(new Paragraph("  "));
            document.add(new Paragraph("  "));
            document.add(new Paragraph("  "));
            document.add(new Paragraph("                This is an Automatic Generated Invoice.   If there is any problem ,Please contact us..."));
            document.add(new Paragraph("                 Phone no : 0452274364   Fax : +94 (0)  45 2262210   Email : galpaditenna@gmail.com"));
            
            document.close();
            
            JOptionPane.showMessageDialog(null, "Report is Sucess");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
               }
    }//GEN-LAST:event_PrintMonthlyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeaLeafStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeaLeafStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeaLeafStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeaLeafStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeaLeafStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton PrintDailyButton;
    private javax.swing.JButton PrintMonthlyButton;
    private javax.swing.JButton homebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable monthtable;
    private javax.swing.JTable stocktable;
    // End of variables declaration//GEN-END:variables
}
