/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpackage;

import java.awt.Image;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class NEW extends javax.swing.JFrame {

    String ImgPath = null;
    private byte[] person_image = null;

    /**
     * Creates new form New
     */
    public NEW() {
        initComponents();
        show_user();
    }
    int pos = 0;

    public Connection getConnection() {
        Connection con = null;

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/teadb", "root", "");
            return con;
        } catch (SQLException ex) {
            Logger.getLogger(NEW.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }

    public ImageIcon ResizeImage(String imagePath, byte[] pic) {
        ImageIcon myImage = null;

        if (imagePath != null) {
            myImage = new ImageIcon(imagePath);
        } else {
            myImage = new ImageIcon(pic);
        }

        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(PIC.getWidth(), PIC.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;

    }

    public ArrayList<Driver> driverList() {
        ArrayList<Driver> driverList = new ArrayList<>();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/teadb", "root", "");

            String query1 = "SELECT * FROM driverz";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            Driver driver;
            while (rs.next()) {
                driver = new Driver(rs.getInt("ID"), rs.getString("type"), rs.getString("driverName"), rs.getString("password"), rs.getString("register"), rs.getString("service"), rs.getString("address"), rs.getString("telNO"), rs.getString("truckNO"), rs.getString("capasity"), rs.getString("nicNO"), rs.getString("route"), rs.getBytes("image"));
                driverList.add(driver);
            }

        } catch (Exception e) {
            Logger.getLogger(NEW.class.getName()).log(Level.SEVERE, null, e);
        }
        return driverList;
    }

    public void show_user() {
        ArrayList<Driver> list = driverList();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_User.getModel();
        model.setRowCount(0);
        Object[] row = new Object[13];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getID();
            row[1] = list.get(i).gettype();
            row[2] = list.get(i).getdriverName();
            row[3] = list.get(i).getpassword();
            row[4] = list.get(i).getregister();
            row[5] = list.get(i).getservice();
            row[6] = list.get(i).getaddress();
            row[7] = list.get(i).gettelNO();
            row[8] = list.get(i).gettruckNO();
            row[9] = list.get(i).getcapasity();
            row[10] = list.get(i).getnicNO();
            row[11] = list.get(i).getroute();
            row[12] = list.get(i).getImage();

            model.addRow(row);
        }
    }

    public void ShowItem(int index) {
        VH.setText(driverList().get(index).gettype());
        DNAME.setText(driverList().get(index).getdriverName());
        PASS.setText(driverList().get(index).getpassword());
        RE.setText(driverList().get(index).getregister());
        add.setText(driverList().get(index).getaddress());
        TEL.setText(driverList().get(index).gettelNO());
        TRUCK.setText(driverList().get(index).gettruckNO());
        CAPASIT.setText(driverList().get(index).getcapasity());
        AVA.setText(driverList().get(index).getnicNO());
        ROU.setText(driverList().get(index).getroute());

        PIC.setIcon(ResizeImage(null, driverList().get(index).getImage()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TABLE = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ADD1 = new javax.swing.JButton();
        UPDATE1 = new javax.swing.JButton();
        DELETE1 = new javax.swing.JButton();
        ATT1 = new javax.swing.JButton();
        PIC = new javax.swing.JLabel();
        DNAME = new javax.swing.JTextField();
        PASS = new javax.swing.JPasswordField();
        TEL = new javax.swing.JTextField();
        TRUCK = new javax.swing.JTextField();
        CAPASIT = new javax.swing.JTextField();
        AVA = new javax.swing.JTextField();
        ROU = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        VH = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_User = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        searchdata = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        S = new javax.swing.JComboBox();
        RE = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TABLE.setBackground(new java.awt.Color(255, 255, 255));
        TABLE.setForeground(new java.awt.Color(255, 255, 255));
        TABLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLEMouseClicked(evt);
            }
        });
        TABLE.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DRIVER NAME");
        TABLE.add(jLabel1);
        jLabel1.setBounds(420, 110, 120, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("PASSWORD");
        TABLE.add(jLabel2);
        jLabel2.setBounds(30, 200, 110, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("TEL NO.");
        TABLE.add(jLabel3);
        jLabel3.setBounds(30, 360, 70, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ADDRESS");
        TABLE.add(jLabel4);
        jLabel4.setBounds(30, 280, 100, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("TRUCK NO.");
        TABLE.add(jLabel5);
        jLabel5.setBounds(480, 490, 100, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("CAPASITY");
        TABLE.add(jLabel6);
        jLabel6.setBounds(30, 430, 100, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("ROUTE ");
        TABLE.add(jLabel8);
        jLabel8.setBounds(490, 580, 70, 22);

        ADD1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ADD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        ADD1.setText("ADD");
        ADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD1ActionPerformed(evt);
            }
        });
        TABLE.add(ADD1);
        ADD1.setBounds(80, 650, 130, 41);

        UPDATE1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UPDATE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit_pencil.png"))); // NOI18N
        UPDATE1.setText("UPDATE");
        UPDATE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE1ActionPerformed(evt);
            }
        });
        TABLE.add(UPDATE1);
        UPDATE1.setBounds(240, 650, 150, 40);

        DELETE1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DELETE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        DELETE1.setText("DELETE");
        DELETE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETE1ActionPerformed(evt);
            }
        });
        TABLE.add(DELETE1);
        DELETE1.setBounds(410, 650, 140, 41);

        ATT1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ATT1.setText("ATTACH");
        ATT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATT1ActionPerformed(evt);
            }
        });
        TABLE.add(ATT1);
        ATT1.setBounds(490, 420, 110, 31);
        TABLE.add(PIC);
        PIC.setBounds(470, 260, 150, 130);

        DNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNAMEActionPerformed(evt);
            }
        });
        DNAME.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DNAMEKeyTyped(evt);
            }
        });
        TABLE.add(DNAME);
        DNAME.setBounds(570, 100, 220, 40);
        TABLE.add(PASS);
        PASS.setBounds(170, 190, 220, 40);

        TEL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TELKeyTyped(evt);
            }
        });
        TABLE.add(TEL);
        TEL.setBounds(170, 350, 230, 40);
        TABLE.add(TRUCK);
        TRUCK.setBounds(590, 480, 220, 40);
        TABLE.add(CAPASIT);
        CAPASIT.setBounds(170, 420, 230, 50);
        TABLE.add(AVA);
        AVA.setBounds(170, 520, 230, 40);
        TABLE.add(ROU);
        ROU.setBounds(590, 570, 220, 40);

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel9.setText("DRIVERS DETAILS");
        TABLE.add(jLabel9);
        jLabel9.setBounds(180, 0, 420, 30);
        TABLE.add(add);
        add.setBounds(170, 270, 220, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow-back-128.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        TABLE.add(jButton1);
        jButton1.setBounds(1260, 20, 80, 80);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("VEHICLE TYPE");
        TABLE.add(jLabel10);
        jLabel10.setBounds(30, 110, 140, 22);
        TABLE.add(VH);
        VH.setBounds(170, 100, 220, 40);

        jTable_Display_User.setBackground(new java.awt.Color(0, 255, 255));
        jTable_Display_User.setForeground(new java.awt.Color(153, 0, 153));
        jTable_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "VEHICLE TYPE", "DRIVER NAME", "PASSWORD", "REGISTER", "SERVICE", "ADDRESS", "TELNO.", "TRUCKNO.", "CAPASITY", "NIC NO.", "ROUTE", "IMAGES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_Display_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_User);

        TABLE.add(jScrollPane1);
        jScrollPane1.setBounds(790, 240, 540, 220);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("NIC NO.");
        TABLE.add(jLabel11);
        jLabel11.setBounds(30, 520, 80, 40);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        TABLE.add(jButton2);
        jButton2.setBounds(930, 470, 130, 31);

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("PREVIOUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        TABLE.add(jButton3);
        jButton3.setBounds(1100, 470, 130, 31);

        searchdata.setBackground(new java.awt.Color(255, 204, 204));
        searchdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchdataActionPerformed(evt);
            }
        });
        searchdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchdataKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchdataKeyTyped(evt);
            }
        });
        TABLE.add(searchdata);
        searchdata.setBounds(800, 20, 250, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Search by Name");
        TABLE.add(jLabel7);
        jLabel7.setBounds(1070, 30, 160, 16);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("REGISTER");
        TABLE.add(jLabel12);
        jLabel12.setBounds(420, 190, 110, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("SERVICE");
        TABLE.add(jLabel13);
        jLabel13.setBounds(780, 200, 90, 22);

        S.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YES", "NO" }));
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        TABLE.add(S);
        S.setBounds(900, 200, 80, 20);
        TABLE.add(RE);
        RE.setBounds(560, 200, 155, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, 1386, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNAMEActionPerformed

    private void TABLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TABLEMouseClicked

    private void ATT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATT1ActionPerformed
        // TODO add your handling code here:

        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            PIC.setIcon(ResizeImage(path, null));
            ImgPath = path;
        } else {
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_ATT1ActionPerformed

    private void ADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD1ActionPerformed
        // TODO add your handling code here:
        if (VH.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, " vehicle type  is empty");
        } else if (DNAME.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "driver name is empty");
        } else if (PASS.getText().length() < 4) {
            JOptionPane.showMessageDialog(null, "Password is empty");
        } else if (add.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Adress is empty");
        } else if (TEL.getText().length() < 10) {
            JOptionPane.showMessageDialog(null, "Telephone number is incorrect");
        } else if (TRUCK.getText().compareTo("") == 0 && TRUCK.getText().length() < 4) {
            JOptionPane.showMessageDialog(null, "Truck Number is empty");
        } else if (CAPASIT.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Capasity is empty");
        } else if (!AVA.getText().trim().matches("^[0-9]{9}[vVxX]$")) {
            JOptionPane.showMessageDialog(null, "nic no is invalid");
        } else if (ROU.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "route details are empty");
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/teadb", "root", "");
                String query = "insert into driverz(type,driverName,password,register,service,address,telNO,truckNO,capasity,nicNO,route,image)values(?,?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, VH.getText());
                pst.setString(2, DNAME.getText());
                pst.setString(3, PASS.getText());
                pst.setString(4, RE.getText());
                String ava;
                ava = S.getSelectedItem().toString();
                pst.setString(5, ava);
                pst.setString(6, add.getText());

                pst.setString(7, TEL.getText());
                pst.setString(8, TRUCK.getText());
                pst.setString(9, CAPASIT.getText());
                pst.setString(10, AVA.getText());
                pst.setString(11, ROU.getText());

                InputStream img = new FileInputStream(new File(ImgPath));
                pst.setBlob(12, img);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Insert Sucessfully");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }
            show_user();
    }//GEN-LAST:event_ADD1ActionPerformed
    }
    private void DELETE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETE1ActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to delete?", "Delete", JOptionPane.YES_NO_OPTION);
        if (opt == 0) {
            if (!DNAME.getText().equals("")) {
                try {
                    Connection con = getConnection();
                    PreparedStatement ps = con.prepareStatement("DELETE FROM driverz WHERE telNO = ?");
                    int tel = Integer.parseInt(TEL.getText());
                    ps.setInt(1, tel);
                    ps.executeUpdate();
                    show_user();
                    JOptionPane.showMessageDialog(null, "Product Deleted");
                } catch (SQLException ex) {
                    Logger.getLogger(NEW.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Product Not Deleted");

                }

            } else {
                JOptionPane.showMessageDialog(null, "Product Not Deleted : No Id To Delete");
            }
        }

    }//GEN-LAST:event_DELETE1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new AdminPannel().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable_Display_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_UserMouseClicked
        // TODO add your handling code here:
        int index = jTable_Display_User.getSelectedRow();
        ShowItem(index);
    }//GEN-LAST:event_jTable_Display_UserMouseClicked

    private void UPDATE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE1ActionPerformed
        // TODO add your handling code here:
         int x = JOptionPane.showConfirmDialog(null, "Do you want to Update ?");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/teadb", "root", "");
            int row = jTable_Display_User.getSelectedRow();
            String value = (jTable_Display_User.getModel().getValueAt(row, 0).toString());

            String query = "UPDATE driverz SET type=?,driverName=?,password=?,register=?,service=?,address=?,telNO=?,truckNO=?,capasity=?,nicNO=?,route=?,image=? WHERE ID=" + value;
            PreparedStatement pst = con.prepareStatement(query);

            pst.setString(1, VH.getText());
            pst.setString(2, DNAME.getText());
            pst.setString(3, PASS.getText());
            pst.setString(4, RE.getText());
            String ava;
            ava = S.getSelectedItem().toString();
            pst.setString(5, ava);
            pst.setString(6, add.getText());

            pst.setString(7, TEL.getText());
            pst.setString(8, TRUCK.getText());
            pst.setString(9, CAPASIT.getText());
            pst.setString(10, AVA.getText());
            pst.setString(11, ROU.getText());
            InputStream img = new FileInputStream(new File(ImgPath));
            pst.setBlob(12, img);

            pst.executeUpdate();
            show_user();
            JOptionPane.showMessageDialog(null, "update Sucessfully");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }


    }//GEN-LAST:event_UPDATE1ActionPerformed

    private void searchdataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchdataKeyReleased
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/teadb", "root", "");
            String sql = "SELECT * from driverz where driverName = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, searchdata.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String settype = rs.getString("type");
                VH.setText(settype);

                String setdname = rs.getString("driverName");
                DNAME.setText(setdname);

                String setregister = rs.getString("register");
                RE.setText(setregister);

                String setaddress = rs.getString("address");
                add.setText(setaddress);

                String settelNO = rs.getString("telNO");
                TEL.setText(settelNO);

                String settruckNo = rs.getString("truckNO");
                TRUCK.setText(settruckNo);

                String setcapasity = rs.getString("capasity");
                CAPASIT.setText(setcapasity);

                String setnic = rs.getString("nicNO");
                AVA.setText(setnic);

                String setroute = rs.getString("route");
                ROU.setText(setroute);

                byte[] img = rs.getBytes("image");
                ImageIcon imageicon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(PIC.getWidth(), PIC.getHeight(), Image.SCALE_SMOOTH));
                PIC.setIcon(imageicon);
                person_image = img;

            }

        } catch (Exception e) {
            Logger.getLogger(NEW.class.getName()).log(Level.SEVERE, null, e);
        }


    }//GEN-LAST:event_searchdataKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        pos++;

        if (pos >= driverList().size()) {
            pos = driverList().size() - 1;
        }

        ShowItem(pos);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pos--;

        if (pos < 0) {
            pos = 0;
        }

        ShowItem(pos);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchdataActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SActionPerformed

    private void TELKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TELKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_TELKeyTyped

    private void searchdataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchdataKeyTyped
        // TODO add your handling code here:
        if (!Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_searchdataKeyTyped

    private void DNAMEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DNAMEKeyTyped
        // TODO add your handling code here:
         if (!Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_DNAMEKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD1;
    private javax.swing.JButton ATT1;
    private javax.swing.JTextField AVA;
    private javax.swing.JTextField CAPASIT;
    private javax.swing.JButton DELETE1;
    private javax.swing.JTextField DNAME;
    private javax.swing.JPasswordField PASS;
    private javax.swing.JLabel PIC;
    private datechooser.beans.DateChooserCombo RE;
    private javax.swing.JTextField ROU;
    private javax.swing.JComboBox S;
    private javax.swing.JPanel TABLE;
    private javax.swing.JTextField TEL;
    private javax.swing.JTextField TRUCK;
    private javax.swing.JButton UPDATE1;
    private javax.swing.JTextField VH;
    private javax.swing.JTextField add;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_User;
    private javax.swing.JTextField searchdata;
    // End of variables declaration//GEN-END:variables

}
