/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transpackage;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author user
 */
public class Splashgo extends javax.swing.JFrame {
     private Splashgo.Animator paint = new Splashgo.Animator();
    private String[] loadingText = {"Loading...", "Initializing...", "Loading modules...", "Loading plug-in...", "Scanning database...", "Finding data...", "Loading data...", "Loading libraries...", "Finalizing...", "Starting..."};
    //private final ImageIcon icon = new ImageIcon(getClass().getResource("/images/Splash/x.png"));
    private int t = 0, cx = 0, cy = 0;
    /**
     * Creates new form splash
     */
    public Splashgo() {
        initComponents();
         int x = (int) ((Toolkit.getDefaultToolkit().getScreenSize().getWidth() - getWidth()) / 2);
        int y = (int) ((Toolkit.getDefaultToolkit().getScreenSize().getHeight() - getHeight()) / 2);
        setLocation(x, y);

       jPanel1.setOpaque(false);
        jPanel1.setBounds(0, 0, getWidth(), getHeight());
        cx = (int) jPanel1.getBounds().getCenterX();
        cy = (int) jPanel1.getBounds().getCenterY();

        new Thread(new Runnable() {
            @Override
            public void run() {
                for (t = 0; t < 100; t++) {
                    jProgressBar1.setValue(t);
                    setprogressLabel(t);
                   jPanel1.repaint();
                    try {
                        if (t < 20) {
                            Thread.sleep(50);
                        } else if (t < 50) {
                            Thread.sleep(90);
                        } else if (t < 75) {
                            Thread.sleep(Math.abs(t - 100));
                        } else if (t < 90) {
                            Thread.sleep(40);
                        } else {
                            Thread.sleep(30);
                        }
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
                new Loginsystem().setVisible(true);
                dispose();
            }
        }).start();
    }
    private class Animator {

        public void draw(Graphics g) {

            int v = (t <= 100) ? t : 100;
            int q = (t <= 100) ? t : 100;

            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
            g2.rotate(((0.05 * Math.PI) * v), cx, cy);
            //g2.drawImage(icon.getImage(), (cx - (icon.getIconWidth() / 2)), (cy - (icon.getIconHeight() / 2)), null);
        }
    }
    private class Animator1 {

        public void draw(Graphics g) {

            int v = (t <= 100) ? t : 100;
            int q = (t <= 100) ? t : 100;

            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
            g2.rotate(((0.05 * Math.PI) * v), cx, cy);
            //g2.drawImage(icon.getImage(), (cx - (icon.getIconWidth() / 2)), (cy - (icon.getIconHeight() / 2)), null);
        }
    }

    /**
     * Creates new form Splashgo
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setBackground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setForeground(new java.awt.Color(255, 41, 16));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 250, 10));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setText("Tea factory");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 190, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main-img.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 460));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splashgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splashgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splashgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splashgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splashgo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
private void setprogressLabel(int t) {

        int v = (t <= 100) ? t : 100;

        int i = 0;
        if (v < 10) {
            i = 0;
        } else if (v < 20) {
            i = 2;
        } else if (v < 25) {
            i = 3;
        } else if (v < 33) {
            i = 4;
        } else if (v < 45) {
            i = 4;
        } else if (v < 60) {
            i = 5;
        } else if (v < 75) {
            i = 6;
        } else if (v < 80) {
            i = 6;
        } else if (v < 88) {
            i = 7;
        } else if (v <= 100) {
            i = 9;
        }
       jLabel4.setText(loadingText[i]);

    }
}