/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HRManagmentInterfaces;

import DBConnect.DBconnect;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lap.lk
 */
public class CalculateSal extends javax.swing.JFrame {

    Connection c = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form CalculateSal
     */
    public CalculateSal() throws ClassNotFoundException, SQLException {
        initComponents();
        
        c = DBconnect.getConnection();
        
        Toolkit toolkit = getToolkit();

    }

    public void clear(){
    
        txtempid.setText("");
        txt_ename.setText("");
        txt_bsal.setText("");
        txt_ot.setText("");
        txt_hrs.setText("");
        txt_increments.setText("");
        txt_deduction.setText("");
        txt_status.setText("");
        
    }
    
    public void demo(){
    
    
        txtempid.setText("20");
        txt_ename.setText("dulaj");
        txt_bsal.setText("30000");
        txt_ot.setText("2000");
        txt_hrs.setText("2");
        txt_increments.setText("500");
        txt_deduction.setText("200");
        txt_status.setText("active");
        
    
    
    
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtempid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_bsal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_ename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_ot = new javax.swing.JTextField();
        txt_hrs = new javax.swing.JTextField();
        txt_increments = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_deduction = new javax.swing.JTextField();
        lbl_sal = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_deduction = new javax.swing.JLabel();
        lbl_increments = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        datebox = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculatesalarydilusha.jpg"))); // NOI18N
        jLabel1.setText("                     CALCULATE SALARY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("EMPLOYEE ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, -1));

        txtempid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempidActionPerformed(evt);
            }
        });
        txtempid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtempidKeyReleased(evt);
            }
        });
        getContentPane().add(txtempid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("BASIC SALARY");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 120, -1));

        txt_bsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bsalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_bsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("EMPLOYEE NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 130, 20));
        getContentPane().add(txt_ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 170, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("OT RATE(RS)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 255));
        jLabel6.setText("OT HOURS(HRS)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 255));
        jLabel7.setText("INCREMENTS(RS)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 130, 20));
        getContentPane().add(txt_ot, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 170, 30));
        getContentPane().add(txt_hrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 170, 30));
        getContentPane().add(txt_increments, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 170, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculator.png"))); // NOI18N
        jButton2.setText("CALCULATE SALARY");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 240, 70));

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PDF.png"))); // NOI18N
        jButton3.setText("pdf CREATE");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 170, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 255));
        jLabel8.setText("DEDUCTION(RS)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 120, 20));
        getContentPane().add(txt_deduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 170, 30));

        lbl_sal.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lbl_sal.setForeground(new java.awt.Color(255, 0, 0));
        lbl_sal.setText("0.00");
        getContentPane().add(lbl_sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 120, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CLEAR.png"))); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 140, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("TOTAL DEDUCTION (Rs)");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 230, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("TOTAL  INCREMENTS(Rs)");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 230, -1));

        lbl_deduction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_deduction.setForeground(new java.awt.Color(255, 0, 0));
        lbl_deduction.setText("0.00");
        getContentPane().add(lbl_deduction, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 70, 20));

        lbl_increments.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_increments.setForeground(new java.awt.Color(255, 0, 0));
        lbl_increments.setText("0.00");
        getContentPane().add(lbl_increments, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 110, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 255, 255));
        jLabel14.setText("STATUS");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 120, 20));
        getContentPane().add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 180, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back2.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 140, 50));

        jButton6.setText("VIEW");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 100, 30));

        jButton5.setText("DEMO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 255, 255));
        jLabel15.setText("Date");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 120, 20));
        getContentPane().add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 180, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shutterstock_360072566.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 910, 430));

        setSize(new java.awt.Dimension(927, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtempidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtempidKeyReleased
        
        try {
            



             Connection c = DBconnect.getConnection();
             Statement s = c.createStatement();
             ResultSet rs = s.executeQuery("SELECT * FROM salary WHERE empid ='"+txtempid.getText()+"'");
            
            
            if(rs.next()){
                txt_ename.setText(rs.getString("empname"));
                txtempid.setText(rs.getString("empid"));
                txt_status.setText(rs.getString("status"));
                txt_bsal.setText(rs.getString("basicsalary"));
            
            
            }else{
            
                JOptionPane.showMessageDialog(rootPane,"INVALID ID!!!");
            }


        } catch (Exception e) {
            
                JOptionPane.showMessageDialog(rootPane, "no data ");
            
        }
        
        
        
        
    }//GEN-LAST:event_txtempidKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        //CALCULATE SALARY BUTTON

       
       double salary = Double.parseDouble(txt_bsal.getText());
  
       
       double otRate = 0;
        try {
            otRate = Double.parseDouble(txt_ot.getText());
            
            
        } catch (NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(null, "pls enter correct ot rate  ");
            return;
        }
       
        if(otRate <= 0){
        
            JOptionPane.showMessageDialog(rootPane, "can,t insert minus values");
        return;
        
        }
        
        
        int otHrs = 0;
        try {
            otHrs = Integer.parseInt(txt_hrs.getText());
        } catch (NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane, "pls enter correct ot hrs ");
            return;
        }
       
        
           if(otHrs <= 0){
        
            JOptionPane.showMessageDialog(rootPane, "can,t insert minus values");
        return;
        
        }
        
        double increments = 0;
        
        try {
            increments = Double.parseDouble(txt_increments.getText());
        } catch (NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane,"pls enter correct increments");
            return;
        }
        
           if(increments <= 0){
        
            JOptionPane.showMessageDialog(rootPane, "can,t insert minus values");
        return;
        
        }
        
        
        double deduction = 0;
        
        try {
            deduction = Double.parseDouble(txt_deduction.getText());
        } catch (NumberFormatException | NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane,"pls enter correct deduction");
            return;
        }
        
        
           if(deduction <= 0){
        
            JOptionPane.showMessageDialog(rootPane, "can,t insert minus values");
        return;
        
        }
        
        
        double totIncrements = increments+(otHrs*otRate);
        double finalSal = salary+totIncrements-deduction;
        lbl_sal.setText(Double.toString(finalSal));
        lbl_deduction.setText(Double.toString(deduction));
        lbl_increments.setText(Double.toString(totIncrements));
       
       
       
       //clear();
       
       //sent to DB 
        try {
            
            int x = JOptionPane.showConfirmDialog(rootPane,"DO YOU WANT TO SAVE THIS?");
            
            if(x == 0){
                c = DBconnect.getConnection();
                Statement s = c.createStatement();
                
                System.out.println("connected!!!!!");
                String empid = txtempid.getText();
                String empname = txt_ename.getText();
                String bsal = txt_bsal.getText();
                String tot_increments = lbl_increments.getText();
                String tot_deduction = lbl_deduction.getText();
                String tot_salary = lbl_sal.getText();
                
                String theDate = " ";
                try{
            
                    Date date = datebox.getDate();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    theDate = dateFormat.format(date);
            
                }catch(NullPointerException e){
                    JOptionPane.showMessageDialog(null, "Please correct the Date");
                    return;
                }
                
                s.executeUpdate("INSERT INTO aftersal (empid,empname,bsalary,increments,deductions,totsalary,date) VALUES ('"+empid+"','"+empname+"','"+bsal+"','"+tot_increments+"','"+tot_deduction+"','"+tot_salary+"','"+theDate+"')");
                
                s.executeUpdate("INSERT INTO finance_hrm (year, month, total) SELECT YEAR(date)as 'Year',MONTHNAME(date)as 'Month', SUM(totsalary) as 'Total value (Rs)' FROM aftersal GROUP BY MONTH(date),YEAR(date) ");

                clear();
            }
            
            
            
        } catch (Exception e) {
                e.printStackTrace();
            
        }
       
       
       
       
       
       
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void txtempidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempidActionPerformed

    private void txt_bsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bsalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home h4 = new Home();
        h4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clear();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        ViewSal v = new ViewSal();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        demo();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateSal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CalculateSal().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CalculateSal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(CalculateSal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker datebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_deduction;
    private javax.swing.JLabel lbl_increments;
    private javax.swing.JLabel lbl_sal;
    private javax.swing.JTextField txt_bsal;
    private javax.swing.JTextField txt_deduction;
    private javax.swing.JTextField txt_ename;
    private javax.swing.JTextField txt_hrs;
    private javax.swing.JTextField txt_increments;
    private javax.swing.JTextField txt_ot;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txtempid;
    // End of variables declaration//GEN-END:variables
}
